bbcode2htmlConfigurator = ->
  transformation :
    '&quot;'                         : '"'                  ,
    '&gt;'                           : '>'                  ,
    '&lt;'                           : '<'                  ,
    '&nbsp;'                         : ' '                  ,
    '\\[u\\]'                        : '<u>'                ,
    '\\[\\/u\\]'                     : '</u>'               ,
    '\\[i\\]'                        : '<em>'               ,
    '\\[\\/i\\]'                     : '</em>'              ,
    '\\[b\\]'                        : '<strong>'           ,
    '\\[\\/b\\]'                     : '</strong>'          ,
    '\\[\\/p\\]'                     : '</p>'               ,
    '\\[p\\]'                        : '<p>'                ,
    '\\[p="([^"]*)"\\]'              : '<p style="$1">'     ,
    '\\[br\\]'                       : '<br/>'              ,
    '\\[\\/h([0-6])\\]'              : '</h$1>'             ,
    '\\[h([0-6])\\]'                 : '<h$1>'              ,
    '\\[\\/code\\]'                  : '</code>'            ,
    '\\[code\\]'                     : '<code>'             ,
    '\\[\\/ul\\]'                    : '</ul>'              ,
    '\\[ul\\]'                       : '<ul>'               ,
    '\\[ul="([^"]*)"\\]'             : '<ul style="$1">'    ,
    '\\[ol\\]'                       : '<ol>'               ,
    '\\[ol="([^"]*)"\\]'             : '<ol style="$1">'    ,
    '\\[span="([^"]*)"\\]'           : '<span style="$1">'  ,
    '\\[span\\]'                     : '<span>'             ,
    '\\[\\/span\\]'                  : '</span>'            ,
    '\\[pre\\]'                      : '<pre>'              ,
    '\\[\\/pre\\]'                   : '</pre>'             ,
    '\\[blockquote\\]'               : '<blockquote>'       ,
    '\\[\\/blockquote\\]'            : '</blockquote>'      ,
    '\\[div\\]'                      : '<div>'              ,
    '\\[\\/div\\]'                   : '</div>'             ,
    '\\[sup\\]'                      : '<sup>'              ,
    '\\[\\/sup\\]'                   : '</sup>'             ,
    '\\[sub\\]'                      : '<sub>'              ,
    '\\[\\/sub\\]'                   : '</sub>'             ,
    '\\[\\/li\\]'                    : '</li>'              ,
    '\\[li\\]'                       : '<li>'               ,
    '\\[table\\]'                    : '<table>'            ,
    '\\[\\/table\\]'                 : '</table>'           ,
    '\\[table="([^"]*)"\\]'          : '<table style="$1">' ,
    '\\[tbody\\]'                    : '<tbody>'            ,
    '\\[\\/tbody\\]'                 : '</tbody>'           ,
    '\\[tr\\]'                       : '<tr>'               ,
    '\\[\\/tr\\]'                    : '</tr>'              ,
    '\\[tr="([^"]*)"\\]'             : '<tr style="$1">'    ,
    '\\[\\/td\\]'                    : '</td>'              ,
    '\\[td\\]'                       : '<td>'               ,
    '\\[td="([^"]*)"\\]'             : '<td style="$1">'    ,
    '\\[\\/th\\]'                    : '</th>'              ,
    '\\[th\\]'                       : '<th>'               ,
    '\\[th="([^"]*)"\\]'             : '<th style="$1">'    ,
    '\\[url="([^";]*)"](.*?)\\[\\/url\\]' : '<a href="$1">$2</a>',
    '\\[td style="([^"]*)" scope="([^"]*)"\\]' : '<td style="$1" scope="$2">',
    '\\[tr style="([^"]*)" scope="([^"]*)"\\]' : '<tr style="$1" scope="$2">',
    '\\[th style="([^"]*)" scope="([^"]*)"\\]' : '<th style="$1" scope="$2">',
    '\\[img alt="([^"]*)" width="([^"]*)" height="([^"]*)"\\]([^"]*)\\[\\/img\\]' : '<img src="$4" alt="$1" width="$2" height="$3"/>',
    '\\[img width="([^"]*)" height="([^"]*)"\\]([^"]*)\\[\\/img\\]' : '<img src="$3" width="$1" height="$2"/>',
    '\\[img alt="([^"]*)" height="([^"]*)"\\]([^"]*)\\[\\/img\\]' : '<img src="$3" alt="$1" height="$2"/>',
    '\\[img alt="([^"]*)" width="([^"]*)"\\]([^"]*)\\[\\/img\\]' : '<img src="$3" alt="$1" width="$2"/>',
    '\\[img height="([^"]*)"\\]([^"]*)\\[\\/img\\]' : '<img src="$2" height="$1"/>',
    '\\[img width="([^"]*)"\\]([^"]*)\\[\\/img\\]' : '<img src="$2" width="$1"/>',
    '\\[img alt="([^"]*)"\\]([^"]*)\\[\\/img\\]' : '<img src="$2" alt="$1"/>',
    '\\[url href="([^"]*)" target="([^"]*)" title="([^"]*)"\\]([^"]*)\\[\\/url\\]' : '<a href="$1" target="$2" title="$3">$4</a>',
    '\\[url href="([^"]*)" target="([^"]*)"\\]([^"]*)\\[\\/url\\]' : '<a href="$1" target="$2">$3</a>',
    '\\[url href="([^"]*)" title="([^"]*)"\\]([^"]*)\\[\\/url\\]' : '<a href="$1" title="$2">$3</a>',
    '\\[url href="([^"]*)"\\]([^"]*)\\[\\/url\\]' : '<a href="$1">$2</a>'

  getTransformation: () ->
    return @transformation

  addTransformation: (tra) ->
    $.extend @transformation, tra
    return

bbcode2html = new bbcode2htmlConfigurator()
